# Generated by Django 3.2.3 on 2021-06-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210601_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caregory',
            new_name='category',
        ),
    ]
